# -*- coding: utf-8 -*-
"""LGM-TASK-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MkE0dKzmig-PEYb7fTLCVcFpoGchLUIn
"""

pip install opencv-python

import cv2
import matplotlib.pyplot as plt

image = cv2.imread("/content/naruto.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
plt.figure(figsize=(8,6))
plt.imshow(image)
plt.axis('off')
plt.title('original image')
plt.show()

gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
plt.figure(figsize=(8,6))
plt.imshow(gray_image, cmap='gray')
plt.axis('off')
plt.title('gray image')
plt.show()

inverted_image = 255 - gray_image
plt.figure(figsize=(8,6))
plt.imshow(inverted_image,cmap='gray')
plt.axis('off')
plt.title('inverted image')
plt.show()

blurred_image = cv2.GaussianBlur(inverted_image, (21, 21), 0)
plt.figure(figsize=(8,6))
plt.imshow(blurred_image,cmap='gray')
plt.axis('off')
plt.title('Blurred Inverted image')
plt.show()

inverted_blurred = 255 - blurred_image
pencil_sketch = cv2.divide(gray_image, inverted_blurred, scale=256.0)
plt.figure(figsize=(8,6))
plt.imshow(pencil_sketch,cmap='gray')
plt.axis('off')
plt.title('Pencil Sketch')
plt.show()